### ISSUE TITLE
Putting keys in planetext in the code

### ISSUE THREAD

**Issue by rashamalek** [Mr0Null/githubfa#2]
Putting keys in plane text makes everyone to abuse the twitter account.

consumer_key = 'xxxx'
consumer_secret = 'xxxx'
access_token = 'xxxx'
access_token_secret = 'xxxx'

**Comment by Alirezaies** [comment]
@rashamalek +1
access token should be removed

better have a `config.ini` which returns tokens and include it in `.gitginore`

**Comment by mavahedinia** [comment]
guys don't worry the tokens are revoked :)) however sadegh is right! I will add a config file and add it in gitignore :)
